[package]
name = "hyperdot-node"
version = "0.1.0"
edition = "2021"

[dependencies]
hyperdot-common-rpc = { path = "../hyperdot-common/rpc"}

jsonrpsee = { version = "0.18.2", features = ["full"]}
serde = { version = "1.0" }
serde_json = { version = "1.0" }
anyhow = { version = "1.0" }
futures = { version = "0.3" }
tokio = { version = "1", features = ["full"] }
subxt = { version = "0.28" }
hex = { version = "0.4.3" }
async-trait = { version = "0.1" }
tokio-postgres = { version = "0.7", features = ["with-bit-vec-0_6"] }
bit-vec = { version = "0.6" }

[build-dependencies]
    